### ISSUE TITLE
Autotimer doesn't work from Openwebif

### ISSUE THREAD

**Issue by cryptontgn** [E2OpenPlugins/e2openplugin-OpenWebif#1015]
It works fine direct from de Vuplus, but in openwebif, i can't do anything, only this advice.

<html> <head><title>500 - Request did not return bytes</title></head> <body> <h1>Request did not return bytes</h1> <p>Request: <pre>&lt;Request at 0x9b1afd50 method=GET uri=/autotimer clientproto=HTTP/1.1&gt;</pre><br />Resource: <pre>&lt;Plugins.Extensions.OpenWebif.controllers.AT.ATController instance at 0x9b1c18a0&gt;</pre><br />Value: <pre>None</pre></p> </body> </html>

Thanks.

**Comment by jbleyel** [comment]
Since when?

Please provide the output of http://<IP of the box>/api/about here.

**Comment by ims21** [comment]
No problem in OpenPLi and Autotimer in Owif

**Comment by ims21** [comment]
http://ipbox/api/about works on all my boxes (OpenPLi)

**Comment by omo42** [comment]
I have the same problem using a Vu+ Solo 4K with OpenWebif on OpenATV 6.3.0. If I click on AutoTimers in the sidebar, nothing happens, when using the _new design_.  But they do work, if I switch back to the OpenWebif  _old design_. So this issue is only in the new design.

The problem arose at the time, when there also was an issue with the normal timers ([mid April 2020](https://www.opena.tv/openatv-6-3-public-stable-image-rueckmeldungen/51753-openwebif-funktioniert-ploetzlich-nicht-mehr-wie-ueblich-unter-6-3-0-stable.html?highlight=OpenWebif)). The timer issue was fixed, the AutoTimer issue is still there.
