### ISSUE TITLE
Can't download M3U for complete bouquet in new design WebIf?

### ISSUE THREAD

**Issue by mensa84** [E2OpenPlugins/e2openplugin-OpenWebif#1197]
Hello,

why isn't it possible anymore to download a M3U file for whole bouquet by clicking on bouquet name in new design WebIf?
I think that already was possible in earlier versions of new design. Could you please make that available again?

**Comment by wedebe** [comment]
Hi @mensa84 , could you screenshot where in the interface you're referring to, please?

**Comment by mensa84** [comment]
@wedebe Yes, of course. I mean that section (in earlier versions I was able to download the whole bouquet in one m3u by clicking on the bouquet name"):

![image](https://user-images.githubusercontent.com/30125802/102646368-2f3d1780-4164-11eb-8831-94e5fa440883.png)

**Comment by wedebe** [comment]
I'm curious to know which app you use the playlist in, and how often you load a playlist... from the point of User Experience I reckon that feature might be better suited as part of the Bouquet Editor or a dedicated playlist import/export page 🤔

Ideas and suggestions very welcome on this

**Comment by Grumpy-Geoff** [comment]
> I'm curious to know which app you use the playlist in, and how often you load a playlist...

One can use VLC or PotPlayer to play the .m3u8 file and stream the services, switching between services by using the player's track switching mechanism.



> from the point of User Experience I reckon that feature might be better suited as part of the Bouquet Editor or a dedicated playlist import/export page 🤔
> 
> Ideas and suggestions very welcome on this

Given one only needs to download the playlist once per bouquet update, and that this functionality still works in the classic design, there's a work-around.

**Comment by mensa84** [comment]
It worked in the new design already, why does it not work anymore now?

**Comment by wedebe** [comment]
Playlists will soon be re-introduced via the Bouquet Editor, stay tuned...

<img width="644" alt="Screen Shot 2021-01-02 at 17 00 15" src="https://user-images.githubusercontent.com/9741693/103462319-4eb77100-4d1c-11eb-8856-e180976ac50c.png">

**Comment by jbleyel** [comment]
Why not readd the link in bouquets as befor.

**Comment by wedebe** [comment]
Downloading a playlist from an icon in a tabbed section of an interface isn't expected behaviour for a novice user. A tab's sole function should be to change the content related to it. 

Most users won't understand why tabbing in the Now/Next channel list will cause a playlist to download sometimes or change the list of channels below other times. Additionally, each channel can already be streamed from the Now/Next channel list.

Making the playlist available using a dedicated, relatable icon from the Bouquet List in the Bouquet Editor - I believe - leads to a more predictable user experience. Which would lead me to suggest the BQE be referred to as Bouquet Manager, but that's another day's work :)

**Comment by wedebe** [comment]
#1207 implements playlist link in the bouquet list.
