### ISSUE TITLE
HLS streaming?

### ISSUE THREAD

**Issue by rdougan** [E2OpenPlugins/e2openplugin-OpenWebif#305]
Currently the streaming is using RTSP, however I'm trying to figure out if this is done via Open Webif or done via something else (enigma, the device). Ideally, to better support iOS (via browser and apps) the HLS protocol should be adopted.

I'm trying to figure out how to go about this (I'm normally an iOS developer, not python) - could someone be so kind to point me in the right direction?

**Comment by jbleyel** [comment]
You are not on the right place here.
The openwebif has nothing todo with streaming.

But i can tell you one thing.
I'm a iOS developer too and i try to improve the streaming on iOS devices since 2012.
I can tell you: "NO chance"

The VU+ transcoding is a step in the right direction but not perfect.
The Dreambox RTSP transcoded stream is a different solution but also not perfect.

You only can contact the box manufactors to improve there transcoding chips.
Software transcoding is absolut impossible with the current CPU's.

**Comment by rdougan** [comment]
@jbleyel thanks! I had a feeling that was the answer. I'll have to setup my own server and do it that way..

**Comment by eriksl** [comment]
RTP/RTSP/HLS/HTTP is all just encapsulation. It's light enough for the processor to do in software. The demuxers and the transconders give mpeg transport stream, but they could be converted to RTP or HLS on the fly in software. We only need a volunteer to implement it...

**Comment by rdougan** [comment]
@eriksl if that's the case, I would be willing to pay someone to make the change so HLS streams are available.

**Comment by eriksl** [comment]
I hear the bounty is on! ;)

**Comment by jbleyel** [comment]
@rdougan : i will repeat "NO CHANCE"  / You can only pay broadcom for a new chip. 
That's no joke.

@eriksl : The problem is not the transport stream, the problem is the original stream format. 
Apple allows only a few formats for hardware decoding.
All other formats needs to decoded on the iOS device without GPU using software. (without jb)
In addition, apple allows only a few transport streams. RTS,RTSP -> NOT

**Comment by eriksl** [comment]
Apple hardware can play the h264 that's embedded in the transport stream. Mpeg2 maybe too, I am not sure. So it's only re-encapsulation.

**Comment by jbleyel** [comment]
MPEG2 -> definitiv NO (Apple does not have a MPEG2 license)

See -> https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html#//apple_ref/doc/uid/TP40008332-CH102-SW1

**Comment by eriksl** [comment]
I haven't had any mpeg2 channels for a long time now ;)

**Comment by rdougan** [comment]
Again, if someone can get an HLS stream from enigma I will pay them. Hit me up and we can discuss.
