### ISSUE TITLE
Request: OpenWebif for Dreambox 7080??

### ISSUE THREAD

**Issue by rako123** [E2OpenPlugins/e2openplugin-OpenWebif#308]
Hello, would it be possible to create and support a version supporting the oe2.2 from Dream Multimedia for the DM7080 and the DM820? On those boxes a .deb package is needed.
In my view, this webif is more advanced than the original one from dream multimedia.

BR, rako123

**Comment by Schimmelreiter** [comment]
Certain/many parts of E2 have been rewritten for DreamOS.
Adapting the OWIF for DreamOS requires quite a lot of changes, which is a lot of work not on the schedule yet.

**Comment by rako123** [comment]
Thanks for coming back on that request. It's areal pity.

**Comment by Schimmelreiter** [comment]
If someone else is going to make the changes and provides a pull request, it can be implemented very fast.
It's just that none of the active devs has a Dreambox.

The easiest would be to create some module on DreamOS which provides the old API functions, so that OWIF (And possibly other plugins) can continue to run on DreamOS.

Or:
Create a module that can provide the relevant DreamOS API calls on E2 and rewrite OWIF to use the DreamOS API plus this module.

See the owibranding.py for example:
Images without the branding module import "owibranding" to have access to the necessary subset of branding functions also on images without own branding.
On images that **do** have oe-alliance-branding, it doesn't get used at all but instead the real, image-provided branding module gets loaded.
