### ISSUE TITLE
OWI Branding: Detection order

### ISSUE THREAD

**Issue by athoik** [E2OpenPlugins/e2openplugin-OpenWebif#325]
Hi,

I have a box where both vumodel (ultimo), boxtype (osmini) and model (dm800se) exists.

Currenlty it is detected as an Vu+ box because the vumodel check if before boxtype check.

Do you think it's ok to change detection order and use boxtype before vumodel?

I will ask for proc entry removal, although there might be a reason that vumodel entry exists, to make some closed source binaries happy, just like model (for some old cam detection).

What do you think? Make the change and see how it goes?

**Comment by athoik** [comment]
Bogus entry will be removed.

**Comment by AbuBaniaz** [comment]
Other manufacturer's also eave the Vu box type entry in so that the softcam checks pass.

It would be great to make the Vu check last.

**Comment by Schimmelreiter** [comment]
The order is very critical, because not only do other vendors have Vu+ entries, but also does Vu+ have Dream entries ...

I'm so happy that this is none of your or my businesses, as the owibranding.py is not used - actually not even shipped - on oe-a images, instead the same info is derived from oe-a branding module.

So we can happily leave the messing around with run-time detection to those who use it in their images **g**
