### ISSUE TITLE
new-theme web-if & ATV software update

### ISSUE THREAD

**Issue by RobvanderDoes** [E2OpenPlugins/e2openplugin-OpenWebif#416]
This issue is on current ATV (2016-11-02 on Xtrend 8k):
As soon as I click on 'Softwareupdate' the WEB-IF is stuck (meaning nothing can be chosen any more) and reloading the page is required.
Maybe related: the option 'Softwareupdate' shows options that are not even available in ATV (but they are in ViX).

**Comment by Schimmelreiter** [comment]
Works for me.
![image](https://cloud.githubusercontent.com/assets/2022025/19957184/a75598e2-a194-11e6-874f-4383a9531431.png)

Which browser, browser version and OS?

About the options itself:
Which options get shown and wether this makes sense or not is decided by E2 and is not up to OWIF to decide.

**Comment by RobvanderDoes** [comment]
But can you leave the above screen and open other screens?
Tested this on current FF & Chrome, as well as on IE11, all with the same result.

**Comment by RobvanderDoes** [comment]
And same under Windows 7 professional.

**Comment by RobvanderDoes** [comment]
To me it looks like to be related with non-existing settings, as all other screens are fine.

**Comment by Schimmelreiter** [comment]
Tested using FF, Chrome and IE in Windows 7: Not reproducable.

Non-existant settings are impossible because OWIF gets them from E2, it does know nothing about them.

All that OWIF does is
- read the setup.xml of E2
- scan for certain section ("usage", "userinterface", "recording", "subtitlesetup", "autolanguagesetup", "avsetup", "harddisk", "keyboard", "timezone", "time", "osdsetup", "epgsetup", "display", "remotesetup", "softcamsetup", "logs", "timeshift", "channelselection", "epgsettings", "softwareupdate", "pluginbrowsersetup")
- **if** one or more of the above sections exist, read the settings within and show them

So only sections that **really** exist within setup.xml and only the options that really exist inside those sections will appear in OWIF.

Which version of OpenATV are you trying?
Maybe you are using a bad setup.xml (From a backup maybe)?

**Comment by RobvanderDoes** [comment]
> This issue is on current ATV (2016-11-02 on Xtrend 8k):

**Comment by Schimmelreiter** [comment]
Current can mean 5.3 or the 6.0 beta or even the 5.4 beta.

But what about this:
"Maybe you are using a bad setup.xml (From a backup maybe)?"


Compare your /usr/share/enigma2/setup.xml 
with the version here:
5.3: https://github.com/openatv/enigma2/blob/master/data/setup.xml
6.0: https://github.com/openatv/enigma2/blob/DEV/data/setup.xml
Or just download the (raw) version and replace yours using it.
Then retry.

**Comment by RobvanderDoes** [comment]
Ah, sorry, 5.3 it is.
I did indeed replace the file stup.xml by the current one from GiT, but this makes no difference.

**Comment by Schimmelreiter** [comment]
Please open
http://<boxname>/ajax/config?section=softwareupdate
and paste the result.

**Comment by RobvanderDoes** [comment]
Softwareupdate
Background check 	
Allow unstable (untested) updates 	
Automatic setting backup 	
Automatic image backup

**Comment by Schimmelreiter** [comment]
Hm
Clear browser cache.
No other ideas.

As I said, works for me.

**Comment by RobvanderDoes** [comment]
Cache in FF is disabled; in Chrome & IE the WEB-IF was opened for the very first time.
Anyway: same issue here on two different computers using 3 different browsers.

**Comment by RobvanderDoes** [comment]
I've asked the not-supported settings on the ATV-board (http://www.opena.tv/openatv-5-3-image-rueckmeldungen/29324-software-update-settings-post259178.html#post259178).
