### ISSUE TITLE
Suggestion: Improve some icon placements

### ISSUE THREAD

**Issue by IanSav** [E2OpenPlugins/e2openplugin-OpenWebif#484]
This is a very minor suggestion.  The details are in the image.

![icons](https://cloud.githubusercontent.com/assets/6904736/20648982/e0c0e096-b508-11e6-8871-2301cb2eaaac.jpg)

**Comment by IanSav** [comment]
As another suggestion could a fixed width be applied to the "days" button bar to make each of the days the same width.

![days](https://cloud.githubusercontent.com/assets/6904736/20661268/0598aa7c-b5a2-11e6-8680-a40f0f5a1f13.jpg)

**Comment by jbleyel** [comment]
Image1 : take a look on the html code and you will see why not so easy and why i don't want to change anyhing.

Image2: the buttons are jquery UI buttons -> no chance to do this 
Please think about other languages.

**Comment by neoatomic** [comment]
@IanSav There might be another way to solve this, and also your other reported naming issues.
You could create an en.po and en_GB.po translation file. So when you have set your Enigma2 language to English (us) or English (gb) that translation file will be used instead of the direct source code naming.

That way you could (re)name everything as you proposed without changing the source code itself.
Also for this specific problem you could add a space at the end of `Fri`. that might solve the difference in seize.

Normally i'm in favor to make the changes directly at the source, but i agree with @jbleyel that it would be to much work as all translation files will need changing. And there are more important things to work on. ;)

**Comment by IanSav** [comment]
For the day width I was thinking about using the the CSS styles to specify a "width" for all the day buttons.  The narrowest button should be the widest width of the longest day in any language.  Then make all buttons the same fixed width.  :smile:

@neoatomic: For languages the coded language is meant to be English.  I was simply suggesting that the language could be improved.  On my personal box I use en_AU and patch all the words I don't like.   :wink:

I did create this report as low priority suggestion so I have no problem if this takes a while to be considered.  This is not a bug fix so it can wait.
