### ISSUE TITLE
Feature request: Show 8 days in EPG

### ISSUE THREAD

**Issue by rklrkl** [E2OpenPlugins/e2openplugin-OpenWebif#532]
The Television -> EPG section currently shows 7 days (e.g. Mon-Sun), but in fact the EPG typically covers 8 days (e.g. Mon-Mon) because when the EPG is updated in the morning - I picked mine to update at 06:55 - it does include a full day's listings for now+7 days' time, meaning you have listings for 8 days. Hence, I'd like the EPG to cover 8 days, not 7.

**Comment by Priskvark** [comment]
If one would extend this idea to a more generic solution (not defined to 7, 8 or any other fixed value) you could add a “next”-button to browse forward to any optional day in the future as long as there is EPG information stored. A “back”-button to browse backwards one day at a time would come in handy. The buttons should probably have symbols (← / →) rather than text captions. 

They should also be active within the defined weekdays as a complement to browsing with the day buttons.
