### ISSUE TITLE
Bouqueteditor - not compatible with 5002 services

### ISSUE THREAD

**Issue by doglover3920** [E2OpenPlugins/e2openplugin-OpenWebif#947]
Nowadays, 5002 services are commenplace.
More and more IPTV channels have to openened by the serviceapp.

However channels with a service ref starting with 5002 causes the bouquets not to be loaded into the bouqueteditor of Owif.

Can this be fixed pls.

**Comment by jbleyel** [comment]
please provide a bouquet file as an example /etc/enigma2/userbouquet.ABC.tv
You should remove user, password and link if there are private.

**Comment by doglover3920** [comment]
[userbouquet.dbe00.zip](https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/files/3317711/userbouquet.dbe00.zip)

**Comment by jbleyel** [comment]
The bouquet editor shows all channels with 5002 as <N/A> because of non support of 5002 in enigma2. This needs to fix in enigma2.

`
serviceslist = serviceHandler.list(eServiceReference(sref))

sfulllist = serviceslist and serviceslist.getContent("RN", True)
`

sfulllist should have sref and not 'N/A' as name
